package com.potluck.buffet.helpers;

import java.util.Random;

public class TestValuesGenerator {
    private static final Random random = new Random();

    // Event
    static int MIN_DAY_OFFSET = 0;
    static int MAX_DAY_OFFSET = 90;

    // Participations
    static int MIN_ATTENDEES = 3;
    static int MAX_ATTENDEES = 12;


    public static String getRandomFirstName(){
        int min = 0;
        int max = FIRST_NAMES_LIST.length -1;
        int randomIndex = getRandomNumber(min, max);
        return FIRST_NAMES_LIST[randomIndex];
    }

    public static String getRandomEventTitle(){
        int min = 0;
        int max = EVENTS_TITLE_LIST.length -1;
        int randomIndex = getRandomNumber(min, max);
        return EVENTS_TITLE_LIST[randomIndex];
    }

    public static int getRandomDayOffset() {
        int min = MIN_DAY_OFFSET;
        int max = MAX_DAY_OFFSET;
        return getRandomNumber(min, max);
    }

    public static int getRandomNbAttendees() {
        int min = MIN_ATTENDEES;
        int max = MAX_ATTENDEES;
        return getRandomNumber(min, max);
    }

    public static int getRandomNumber(int min, int max) {
        return random.nextInt(max - min) + min;
    }


    static final String[] FIRST_NAMES_LIST = {
            "absolon",
            "adélaïde",
            "adèle",
            "adolphe",
            "adrien",
            "adrienne",
            "agnès",
            "aimé",
            "aimée",
            "alain",
            "albertine",
            "alexandrie",
            "alphonse",
            "alphonsine",
            "amaury",
            "ambre",
            "ambroise",
            "amédée",
            "amélie",
            "anastasie",
            "anatole",
            "andrée",
            "angèle",
            "angeline",
            "angelique",
            "annette",
            "anselme",
            "antoine",
            "antoinette",
            "apollinaire",
            "apolline",
            "arianne",
            "arienne",
            "aristide",
            "armand",
            "armel",
            "armelle",
            "arnaud",
            "arnaude",
            "aude",
            "auguste",
            "augustin",
            "aurèle",
            "aurélie",
            "aurelien",
            "aurore",
            "axelle",
            "baptiste",
            "barnabé",
            "barthélémy",
            "basile",
            "bastien",
            "baudouin",
            "béatrice",
            "bénédicte",
            "benjamine",
            "benoit",
            "benoite",
            "bernadette",
            "berthe",
            "blaise",
            "brice",
            "camille",
            "carole",
            "cécile",
            "céleste",
            "célestin",
            "célestine",
            "céline",
            "cerise",
            "cesaire",
            "chanté",
            "charline",
            "charlot",
            "chloé",
            "christelle",
            "christophe",
            "claire",
            "clarisse",
            "claudette",
            "claudine",
            "clémence",
            "clément",
            "clementine",
            "clothilde",
            "colette",
            "colombain",
            "colombe",
            "corin",
            "corinne",
            "cosette",
            "cunégonde",
            "cyrille",
            "damien",
            "danièle",
            "delphine",
            "désiré",
            "désirée",
            "didier",
            "dieudonné",
            "dieudonnée",
            "diodore",
            "dominique",
            "donatien",
            "donatienne",
            "doriane",
            "dorothée",
            "edgard",
            "édith",
            "edmond",
            "édouard",
            "edwige",
            "eléonore",
            "éliane",
            "élise",
            "élodie",
            "eloi",
            "éloise",
            "emeline",
            "émile",
            "émilie",
            "émilien",
            "emmanuelle",
            "ermenegilde",
            "esmé",
            "esmée",
            "étienne",
            "eugène",
            "eugénie",
            "eulalie",
            "eustache",
            "évariste",
            "evrard",
            "fabien",
            "fabienne",
            "fabrice",
            "faustine",
            "félicie",
            "felicien",
            "felicienne",
            "félix",
            "fernand",
            "fernande",
            "fiacre",
            "fifi",
            "firmin",
            "flavie",
            "florentin",
            "florette",
            "florianne",
            "franck",
            "françois",
            "françoise",
            "frédéric",
            "frédérique",
            "gaétan",
            "gaetane",
            "gaspard",
            "gaston",
            "gautier",
            "geneviève",
            "geoffroi",
            "georges",
            "georgette",
            "georgine",
            "gérald",
            "gérard",
            "géraud",
            "germain",
            "germaine",
            "gervais",
            "gervaise (2)",
            "ghislain",
            "ghislaine",
            "gigi",
            "gilberte",
            "gilles",
            "gisèle",
            "gratien",
            "grégoire",
            "guillaume",
            "gustave",
            "gwenaelle",
            "hélène",
            "héloïse",
            "henri",
            "henriette",
            "hercule",
            "hervé",
            "hilaire",
            "honoré",
            "honorine",
            "hortense",
            "hugues",
            "hyacinthe",
            "ignace",
            "inès",
            "iréné",
            "irène",
            "irénée",
            "jacinthe",
            "jacques",
            "jean (1)",
            "jean-baptiste",
            "jean-marie",
            "jeanne",
            "jeannette",
            "jeannot",
            "jérémie",
            "jérôme",
            "joceline",
            "joël",
            "joelle",
            "jolie",
            "josée",
            "josèphe",
            "joséphine",
            "josette",
            "josiane",
            "jourdain",
            "jules (1)",
            "julien",
            "julienne",
            "juliette",
            "juste",
            "laure",
            "laurence (2)",
            "laurent",
            "laurentine",
            "laurette",
            "lazare",
            "léa",
            "léandre",
            "léon",
            "léonard",
            "léonce",
            "léonie",
            "léonne",
            "léontine",
            "léopold",
            "lionel",
            "lisette",
            "lothaire",
            "loup",
            "luc",
            "luce",
            "lucie",
            "lucien",
            "lucienne",
            "lucille",
            "lucinde",
            "lucrece",
            "lunete",
            "lydie",
            "madeline",
            "manon",
            "marc",
            "marceline",
            "marcelle",
            "marcellette",
            "marcellin",
            "marcelline",
            "margot",
            "marguerite",
            "marianne (1)",
            "marie",
            "marielle",
            "mariette",
            "marine",
            "marise",
            "martine",
            "mathieu",
            "mathilde",
            "matthieu",
            "maxime",
            "maximilien",
            "maximilienne",
            "mélanie",
            "mélissa",
            "michèle",
            "micheline",
            "mignon",
            "mireille",
            "modeste",
            "modestine",
            "monique",
            "morgaine",
            "morgane",
            "nadine",
            "narcisse",
            "nathalie",
            "nazaire",
            "nicodème",
            "nicolas",
            "nicolette",
            "ninette",
            "ninon",
            "noé",
            "noel",
            "noella",
            "noémie",
            "océane",
            "odette",
            "odile",
            "olivie",
            "olivier",
            "olympe",
            "onesime",
            "oriane",
            "orianne",
            "osanne",
            "ouida",
            "ozanne",
            "papillion",
            "pascal",
            "pascale",
            "pascaline",
            "paschal",
            "patrice",
            "paule",
            "paulette",
            "pénélope",
            "perceval",
            "perrine",
            "philibert",
            "philippe",
            "philippine",
            "pierre",
            "placide",
            "pons",
            "rainier",
            "raoul",
            "raphaël",
            "raymonde",
            "rébecca",
            "régine",
            "régis",
            "reine",
            "rémi",
            "rémy",
            "renaud",
            "rené",
            "renée",
            "reynaud",
            "roch",
            "rochelle",
            "rodolphe",
            "rodrigue",
            "rolande",
            "romain",
            "romaine",
            "rosalie",
            "roselle",
            "rosemonde",
            "rosette",
            "rosine",
            "sacha",
            "salomé",
            "sandrine",
            "sébastien",
            "sébastienne",
            "seraphine",
            "serge",
            "séverin",
            "sévérine",
            "sidonie",
            "simone (1)",
            "solange",
            "stéphane",
            "stéphanie",
            "suzanne",
            "suzette",
            "sylvain",
            "sylvaine",
            "sylvestre",
            "sylviane",
            "sylvianne",
            "sylvie",
            "tatienne",
            "telesphore",
            "theirn",
            "théo",
            "théodore",
            "théophile",
            "thérèse",
            "thibault",
            "thierry",
            "timothée",
            "toinette",
            "toussaint",
            "urbain",
            "valentine (2)",
            "valère",
            "valérie",
            "valéry",
            "véronique",
            "vespasien",
            "victoire",
            "victorine",
            "vienne",
            "violette",
            "virginie",
            "vivien",
            "vivienne",
            "yolande",
            "yseult",
            "yves",
            "yvette",
            "yvonne",
            "zacharie",
            "zephyrine",
            "zoé"};

    private static String[] EVENTS_TITLE_LIST = {"Le vieux Stravinsky commente son Sacre du printemps. Une leçon sur la fiabilité des sources autobiographiques",
"Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Conférence du NeuroClub : Recherche sur l'épilepsie, des souris et des Hommes",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Les géothermies en Suisse: quels potentiels? & EnergéÔ: un projet de géothermie vaudois voisin",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Audits énergétiques: levier pour l'efficacité énergétique et économique",
        "La diplomatie privée ou comment représenter des capitales qui n'existent pas encore",
        "Séminaire énergie-environnement 2021-2022 / Systèmes énergétiques en transition : éléments de réflexion",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "11 octobre: Meet your future employer!",
        "Le sanctuaire extra‐urbain d’Echmoun et d’Astarté près de Sidon (Liban)",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "Conférence \"20 ans de l'OPAC en RDC\", 3éme Conférence",
        "Le programme GEothermies : qu'as-t-on appris et quels résultats à ce jour",
        "Cycle de conférences sur la géothermie - Campagne de prospection du sous-sol genevois",
        "12-14 de l'égalité « Briser le tabou des règles : quels enjeux ? »",
        "Le plan de mobilité genevois: stratégie & prospective",
        "Traduction - Interprétation - Gestion du multilinguisme : un regard d’économiste sur un continuum de choix",
        "Réflexions autour de la détention administrative",
        "Séminaire énergie-environnement 2021-2022 / Systèmes énergétiques en transition : éléments de réflexion",
        "Concert du Chœur de l'Université",
        "Le genre, un marqueur des récits de transfuges de classe",
        "Journée de droit bancaire et financier 2021",
        "Habiter la ville, habiter le climat",
        "Afghanistan: les leçons d'un échec",
        "Parlons numérique",
        "Intelligence artificielle et automatisation des métiers: quels métiers pour le futur?",
        "Parlons numérique",
        "Journée de l'Innovation 2021",
        "Du jaguar au serpent à plumes. Dieux et mythes aztèques",
        "Ethnomusicology Beyond Academia",
        "Vieillissement au travail: les effets de genre en perspective comparative",
        "L’ouverture des frontières aux migrations de travail: une solution à la crise de l’asile?"};


}
